In [1]:
from sklearn.metrics import cohen_kappa_score
import pandas as pd

In [2]:
df = pd.read_excel('all overlap tweet.xlsx', sheet_name=2)
df.head()

,Unnamed: 0,Unnamed: 1,Annotator 5,Unnamed: 3,Annotator 6,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,No,Tweet,Apakah tweet ini mengandung lebih dari 1 jenis...,Apa sentimen yang paling dominan dalam tweet ini?,Apakah tweet ini mengandung lebih dari 1 jenis...,Apa sentimen yang paling dominan dalam tweet ini?,similiarity,similiarity
1,5001,STOP ASIAN HATE STOP ALL HATE Smua Agama ajark...,Tidak,Netral,Tidak,Netral,1,1
2,5002,Dibutuhkan tahapan uji klinik yang berbeda aga...,Tidak,Netral,Tidak,Netral,1,1
3,5003,"@yayan_alfian Padahal di US vaksin gratis, bis...",Ya,Netral,Ya,Netral,1,1
4,5004,Pfizer dan BioNTech mulai uji coba vaksin Covi...,tidak,Netral,Tidak,Netral,1,1

In [3]:
df.drop([0], inplace=True)

df.columns = range(df.columns.size)
df.T.reset_index(drop=True).T
df.columns = range(df.shape[1])

df.rename(columns={0: "No", 1: "Tweet", 2: "A1", 3: "A2", 4: "B1", 5: "B2"}, inplace=True)
df.head()

,No,Tweet,A1,A2,B1,B2,6,7
1,5001,STOP ASIAN HATE STOP ALL HATE Smua Agama ajark...,Tidak,Netral,Tidak,Netral,1,1
2,5002,Dibutuhkan tahapan uji klinik yang berbeda aga...,Tidak,Netral,Tidak,Netral,1,1
3,5003,"@yayan_alfian Padahal di US vaksin gratis, bis...",Ya,Netral,Ya,Netral,1,1
4,5004,Pfizer dan BioNTech mulai uji coba vaksin Covi...,tidak,Netral,Tidak,Netral,1,1
5,5005,Kasus siswa jombang yg meninggal kemarin efek ...,Tidak,Negatif,Tidak,Negatif,1,1

In [4]:
mapping = {'Ya': 1, 'Tidak': 0, 'Netral': 1, 'Positif': 2, 'Negatif': 0}
df.replace({'A1': mapping, 'A2': mapping, 'B1': mapping, 'B2': mapping}, inplace=True)
df.head()

,No,Tweet,A1,A2,B1,B2,6,7
1,5001,STOP ASIAN HATE STOP ALL HATE Smua Agama ajark...,0,1,0.0,1.0,1,1
2,5002,Dibutuhkan tahapan uji klinik yang berbeda aga...,0,1,0.0,1.0,1,1
3,5003,"@yayan_alfian Padahal di US vaksin gratis, bis...",1,1,1.0,1.0,1,1
4,5004,Pfizer dan BioNTech mulai uji coba vaksin Covi...,tidak,1,0.0,1.0,1,1
5,5005,Kasus siswa jombang yg meninggal kemarin efek ...,0,0,0.0,0.0,1,1

In [5]:
rater1 = df['A1'].tolist() + df['A2'].tolist()
rater2 = df['B1'].tolist() + df['B2'].tolist()

print(rater1)
print(rater2)

[0, 0, 1, 'tidak', 0, 0, 0, 'ya', 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, nan, 1, 1, 1, 1, 0, 1, 1, 2, 0, 1, 1, 2, 1, 1, 0, 1, 2, 0, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 0, 2, 1, 0, 1, 1, 1, 1, 1, 0, 1, 2, 2, 2, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 2, 1, 1, 1, 1, 2, 1, 0, 0, 1, 1, 2, 0, 1, 1, 0, 1, 0, 1, 2, 1, 0, 1, 1, 1, 1, 1, 2, 1, 2, 2, 2, 'positif', 1, 1, 'positif', 0, 'netral', 1, 'netral', 2, 1, 1, 'positif', 1, 'positif', 1, 2, 1, 'positif', 'netral', 'negatif', 'negatif', 'netral', 'positif', 0, 0, 2, 0, 1, 0, 1, 0, 2, 2, 1, 1, 2, 1, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 0, 1, 1, 0, 2, 1, 2, 1, 1, 0, 0, 2, 1, 0, 1, 2, 2, 1, 2, 2, 1, 2, 0, 1, 2, 1, 1, 0, 1, 1, 1, 2, 1, 2, 1, 2, 1, 1, 1, 0, 1, nan]
[0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, nan, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 2.0, 0.0, 1.0, 1.0, 2.0, 1.0, 1.0, 0.0, 1.0, 2.0, 0.0, 1.0, 1.0, 2.0, 1.0, 1.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 1.0, 2.0, 1.0, 0.0, 2.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 2.0, 2.0, 2.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 2.0, 1.0, 1.0, 1.0, 1.0, 2.0, 1.0, 0.0, 0.0, 1.0, 1.0, 2.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 2.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 1.0, 2.0, 2.0, 2.0, 2.0, 1.0, 1.0, 2.0, 0.0, 1.0, 1.0, 1.0, 2.0, 1.0, 1.0, 2.0, 1.0, 2.0, 1.0, 2.0, 1.0, 2.0, 1.0, 0.0, 0.0, 1.0, 2.0, 0.0, 0.0, 2.0, 0.0, 1.0, 0.0, 1.0, 0.0, 2.0, 2.0, 1.0, 1.0, 2.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 2.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 2.0, 1.0, 2.0, 1.0, 1.0, 0.0, 0.0, 2.0, 1.0, 0.0, 1.0, 2.0, 2.0, 1.0, 2.0, 2.0, 1.0, 2.0, 0.0, 1.0, 2.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 2.0, 1.0, 2.0, 1.0, 2.0, 1.0, 1.0, 1.0, 0.0, 1.0, nan]

In [6]:
cohen_kappa_score(rater1, rater2)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').